name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Geração do Snake
        uses: Platane/snk@v3
        with:
          github_user_name: RonaldPassosPB
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit do resultado
        uses: EndBug/add-and-commit@v9
        with:
          message: "🐍 Atualizando snake"
          add: "dist/github-contribution-grid-snake.svg"