name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: RonaldPassosPB
          template: classic
          base: header, repositories, activity, community
          config_timezone: America/Sao_Paulo
          commit_branch: main   # adiciona esta linha para salvar na main
